### ISSUE TITLE
OpenHAB 2 Item Example

### ISSUE THREAD

**Issue by codmpm** [aleon-GmbH/aleoncean-openhab-binding#19] opened 2016-06-26 23:37 UTC
Hi guys,

first: Thanks for your work. I finally - without any Java oder Maven knowledge - got the binding compiled and running:

    214 | Active   |  80 | 1.7.5.SNAPSHOT        | openHAB aleoncean Binding
    215 | Active   |  80 | 1.10.0.SNAPSHOT       | aleoncean

My Problem now is, how I can access the device through openhab2's new "channel" adressing. Could you give me an example? Especially for the FUD61NPN according to https://github.com/aleon-GmbH/aleoncean-openhab-binding/blob/master/doc/config/item.md

And: Do I understand it right that i need to Switch FUD61_TEACHIN off-on-off to "pair" the FUD?

I have to admit that this are my first steps with enocean. Got OpenHAB 1 running for quite a while and wanted to extend it with EnOcean.

Thank you

**Comment by maggu2810** [comment] 2016-06-27 08:52
> I finally - without any Java oder Maven knowledge - got the binding compiled and running

Nice :wink: 

This binding has been created for openHAB 1 and could be used in openHAB 2 by using the compat1x (compatibility layer for OH1 bindings).
As it is still an openHAB 1 binding, it does not offer any new feature that are available for Eclipse SmartHome based distribution (e.g. openHAB).

This binding is "out-off-date" and not under further development.
Sorry

**Comment by codmpm** [comment] 2016-06-27 10:06
Hey, thanks for your reply.

Ok, so I can use the aleoncean-binding in openhab2 with the exact same item-syntax as in openhab1?

Sad there is no further development, but I understand that. Do you know if the "official" openhab-enocean-binding will enable switching of (e.g.) the FUD61? As I've read it only can get sensor values and can not switch anything.

Maybe it's better to not rely on openHAB if I want to use enOcean Actuators?
Do you have any suggestion for an alternative to openhab? Most of my items work through mqtt, besides the homematic/max ones which come over homegear, but these could easily be bridged to mqtt.

Thanks for your time.

**Comment by maggu2810** [comment] 2016-06-27 11:15
> Ok, so I can use the aleoncean-binding in openhab2 with the exact same item-syntax as in openhab1?

Yes, that should be possible.

> Do you know if the "official" openhab-enocean-binding will enable switching of (e.g.) the FUD61?

I don't know, but I don't think so.
IIRC this binding supports more devices as the other one (I started this one after I developed some stuff for the other one caused by architectural changes that are necessary).

I don' know another ready to use and open source binding for EnOcean and ESH.

**Comment by codmpm** [comment] 2016-06-27 11:44
Thank you. I will try to teach the FUD61 to my current installation and I will give short feedback for OHb3.

I didn't mean another binding but a replacement for openHAB itself. I'm willing to try something different. Just wanted your suggestion ;)

**Comment by maschenborn** [comment] 2016-06-27 13:01
I had some success with eltako FSR61NP with aleoncean and OH2 - PM me - maybe we can get it to work together?!?

**Comment by codmpm** [comment] 2016-06-27 13:09
Thank you!

**Comment by codmpm** [comment] 2016-07-04 20:07
So after all I can't get it running. Even with the help from @maschenborn who tried everything he can.

My solution now is to use FHEM for my EnOcean devices and use their mqtt-bridge to make the devices available to openhab. Works fast and without any hicups.

Nevertheless thank you for your work!

**Comment by maggu2810** [comment] 2016-07-05 06:30
> My solution now is to use FHEM for my EnOcean devices and use their mqtt-bridge to make the devices available to openhab. Works fast and without any hicups.

Perhaps this is the easiest open source based solution. :wink: 
I used FHEM for EnOcean devices years ago and if there is a MQTT bridge, I don't see any problems.

I assume I can close this issue. Correct?

**Closed by maggu2810** 2016-07-05 06:30 UTC
